### ISSUE TITLE
The calculation of the parameter σ in class-wise kernel?

### ISSUE THREAD

**Issue by youyi-jia** [Cli98/DMNet#1] opened 2021-01-13 13:04 UTC
First of all thanks for sharing.As you mentioned in your paper, you compute σ by estimating the average scale for each object category and estimate σ by applying Eq. 3 
![Uploading QQ截图20210113205604.png…]()
But I don't seem to see this point in this code, can you answer it for me, can you tell me which part of the code shows this part?

**Comment by Cli98** [comment] 2021-01-19 13:59
@youyi-jia Hi and apologize for late reply. 
We have discussed the method to calculate average scale of sigma in the paper. And basically you calculate the scale of each category in training set and assign each sigma to your density map generation process. Hopefully this could help you.

**Comment by youyi-jia** [comment] 2021-01-19 14:27
First of all, thank you for your reply. I have reproduced the content described in your paper according to this code you provided and compared it with the two diagrams in your paper. Since Sigma was not assigned by class, just use the default parameter （    min_sigma = 0， max_sigma = 20， method=3, const_sigma=15） given in this code . And for the size of sliding window, I have counted the average target of each class in the training set and selected the result of the largest bus class as described in your paper. Though the clipping result is a little different from that in your paper, but the general result is the same.And I have another problem, I counted the size of crop images, just found that more than 50% of the image size is small (130 * 130 or so), but some cutting figure very big (1000 * 1400, for example),I want to know how you deal with such a large size gap, and what size do you scale the images to  send them to the network for prediction?Scale small picture to small size and big to big size?How to choose this size?

**Comment by youyi-jia** [comment] 2021-01-19 14:27
@Cli98 
First of all, thank you for your reply. I have reproduced the content described in your paper according to this code you provided and compared it with the two diagrams in your paper. Since Sigma was not assigned by class, just use the default parameter （ min_sigma = 0， max_sigma = 20， method=3, const_sigma=15） given in this code . And for the size of sliding window, I have counted the average target of each class in the training set and selected the result of the largest bus class as described in your paper. Though the clipping result is a little different from that in your paper, but the general result is the same.And I have another problem, I counted the size of crop images, just found that more than 50% of the image size is small (130 * 130 or so), but some cutting figure very big (1000 * 1400, for example),I want to know how you deal with such a large size gap, and what size do you scale the images to send them to the network for prediction?Scale small picture to small size and big to big size?How to choose this size?

**Comment by Cli98** [comment] 2021-01-19 18:19
> @Cli98
> First of all, thank you for your reply. I have reproduced the content described in your paper according to this code you provided and compared it with the two diagrams in your paper. Since Sigma was not assigned by class, just use the default parameter （ min_sigma = 0， max_sigma = 20， method=3, const_sigma=15） given in this code . And for the size of sliding window, I have counted the average target of each class in the training set and selected the result of the largest bus class as described in your paper. Though the clipping result is a little different from that in your paper, but the general result is the same.And I have another problem, I counted the size of crop images, just found that more than 50% of the image size is small (130 * 130 or so), but some cutting figure very big (1000 * 1400, for example),I want to know how you deal with such a large size gap, and what size do you scale the images to send them to the network for prediction?Scale small picture to small size and big to big size?How to choose this size?

@youyi-jia 
1. I did not use the same parameter (sliding window) as what you did but good to hear that you reproduced my result. If possible can you post or reply to me for your validation result? I want to see if there are any difference given a different sliding window.
2.  I do not have 1000 * 1400 (**nearly same scale as input**) in my cropping result. For those crops(>= 1000*1400) you get, density map cropping simply did not work. The reason for this is due to your sliding window setup, you select bus, which is too large. I do not know why you select bus. However the chance for you to generate 1000 * 1400 crops happen should not be the majority due to the internal design mechanism of DMNet. And thus, simply resize them to the same scale should be okay.

**Comment by youyi-jia** [comment] 2021-01-20 01:18
@Cli98 
Ok， I will send you a detailed email.

**Comment by Cli98** [comment] 2021-01-20 01:30
> @Cli98
> Ok， I will send you a detailed email.

Sure. Let's see what's going on.

And I wonder if that's all of your question? If yes, I may close this issue thread for now.

**Comment by youyi-jia** [comment] 2021-01-20 01:33
@Cli98 
OK, I will email you if there are other questions

**Comment by Cli98** [comment] 2021-01-20 01:39
@youyi-jia 
Sure. I will close this issue now. Feel free to open if you have any questions.

BTW, let me know if you are willing to share me with you evaluation result. 

Thank you

**Closed as completed by Cli98** 2021-01-20 01:39 UTC

**Comment by youyi-jia** [comment] 2021-01-20 01:44
@Cli98 
Sure, I am making the final adjustment and testing. After that, I will send the evaluation result and detailed explanation to your email. It will not be later than today.

**Comment by Cli98** [comment] 2021-01-20 02:49
> @Cli98
> Sure, I am making the final adjustment and testing. After that, I will send the evaluation result and detailed explanation to your email. It will not be later than today.

Sure. Let's see how's everything going on.

**Comment by youyi-jia** [comment] 2021-01-20 11:13
@Cli98 
I have sent an email to your cli33@uncc.edu email address, and the interpretation of results is in the attachment.

**Comment by Cli98** [comment] 2021-01-20 16:43
> @Cli98
> I have sent an email to your [cli33@uncc.edu](mailto:cli33@uncc.edu) email address, and the interpretation of results is in the attachment.

Thanks.

**Comment by LeoHG98** [comment] 2023-05-08 07:52
@youyi-jia May I know your contact information?I also hope to be able to exchange some questions about the DMNet project with you.

**Comment by youyi-jia** [comment] 2023-05-08 07:52
已收到
